# Generated by Django 6.0.1 on 2026-01-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(help_text='Use first day of month, e.g. 2026-01-01')),
                ('meal_rate', models.DecimalField(decimal_places=2, help_text='Rate per meal', max_digits=6)),
                ('electricity_bill', models.DecimalField(decimal_places=2, max_digits=8)),
                ('water_bill', models.DecimalField(decimal_places=2, max_digits=8)),
                ('utility_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_month'],
                'unique_together': {('effective_month',)},
            },
        ),
    ]
