# Generated by Django 6.0.1 on 2026-01-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_memberprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='seat_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
